# General Setup
# =============
info:
  app:
    description: Learning Flyway with Spring Boot 2

# Spring Framework Setup
# ======================
spring:
  application:
    name: learn-flyway
  datasource:
    platform: h2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
    hibernate:
      ddl-auto: validate
  # remark because using embedded H2DB
  #flyway:
  #  user: admin
  #  password: password
  #  schemas: test
